/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse a Cooklang recipe text and return the parsed result as JSON. */
export declare function parse(input: string): string
export declare class LspServer {
  constructor()
  sendMessage(message: string): void
  receiveMessage(): Promise<string | null>
}
