/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse a Cooklang recipe text and return the parsed result as JSON. */
export declare function parse(input: string): string
/**
 * Generate a shopping list from one or more Cooklang recipes.
 *
 * - `recipes_json` – JSON array of `{ content: string, scale: number }` objects.
 * - `aisle_conf` – optional aisle configuration text (cooklang shopping-list format).
 * - `pantry_conf` – optional pantry configuration text (TOML format).
 *
 * Returns a JSON-serialized `ShoppingListResult`.
 */
export declare function generateShoppingList(recipesJson: string, aisleConf?: string | undefined | null, pantryConf?: string | undefined | null): string
/** Parse a Cooklang menu file and return a menu-specific JSON structure. */
export declare function parseMenu(input: string, scale: number): string
/**
 * Start a background sync task.
 *
 * Creates a `SyncContext`, attaches a status listener, stores the context
 * globally (so `stop_sync` can cancel it), and spawns a tokio task that
 * calls `cooklang_sync_client::run_async`.
 */
export declare function startSync(recipesDir: string, dbPath: string, syncEndpoint: string, jwt: string, namespaceId: number): void
/**
 * Cancel a running sync operation.
 *
 * Retrieves the global `SyncContext` and calls `cancel()` on it, which
 * triggers cancellation of all child tokens inside the sync client.
 */
export declare function stopSync(): void
/**
 * Return the current sync status as a JSON string.
 *
 * The returned JSON has the shape:
 * ```json
 * { "status": "idle"|"syncing"|"indexing"|"downloading"|"uploading"|"error",
 *   "lastError": "..." | null,
 *   "lastSynced": "2025-01-01T00:00:00Z" | null }
 * ```
 */
export declare function getSyncStatus(): string
/**
 * Register a JS callback that is invoked on every sync status change.
 *
 * The callback receives a JSON string with the same shape as `getSyncStatus`.
 * Replaces any previously registered callback.
 */
export declare function onSyncStatusChanged(callback: (...args: any[]) => any): void
export declare function parseShoppingList(text: string): string
export declare function writeShoppingList(json: string): string
export declare function parseChecked(text: string): string
export declare function writeCheckEntry(entryJson: string): string
export declare function checkedSet(entriesJson: string): Array<string>
/**
 * Resolve a recipe by name (with or without extension) inside `base_dir` using
 * `cooklang-find`'s lookup rules (tries `.cook` then `.menu` when no extension).
 * Returns the file content, or `null` if no matching file is found.
 */
export declare function findRecipe(baseDir: string, name: string): string | null
export declare function compactChecked(entriesJson: string, currentIngredients: Array<string>): string
/**
 * Search recipes under `base_dir` the way `cook search` does
 * (`cooklang_find::search`: filename + content term scoring over `.cook` and
 * `.menu`). A blank query lists every recipe via `cooklang_find::build_tree`.
 *
 * Returns JSON: `[{ path, name, title, tags, isMenu, servings }]`, best match first.
 */
export declare function searchRecipes(baseDir: string, query: string): string
/**
 * Parse a `config/pantry.conf` (TOML) and return its sections and items.
 *
 * Returns JSON: `{ sections: [{ name, items: [{ name, quantity, bought, expire, low, isLow }] }],
 *                  lowStock: [{ name, section, quantity, low }] }`.
 */
export declare function parsePantry(text: string): string
/**
 * Check which of `names` are in the pantry (case-insensitive, via
 * `PantryConf::find_ingredient`).
 *
 * Returns JSON: `[{ name, inStock, section, quantity, isLow }]` in input order.
 */
export declare function checkPantry(text: string, names: Array<string>): string
/**
 * Render a Jinja2 report template against a recipe via cooklang-reports
 * (the same engine cookcli's `cook report` uses).
 *
 * Returns JSON: `{"output": "..."}` on success or `{"error": "..."}` on failure.
 */
export declare function renderReport(recipe: string, template: string, configJson: string): string
export declare class LspServer {
  constructor()
  sendMessage(message: string): void
  receiveMessage(): Promise<string | null>
}
